protocol = "my-daemon"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://github.com/yaq-project/hart-protocol"
bugtracker = "https://github.com/yaq-project/hart-protocol/-/issues"

[installation]
PyPI = "https://pypi.org/project/hart-protocol"

[config]

[state]

[messages]

